## Analisis de Vuelos Norteamericanos 1992-2016 con Python


- Análisis de puntualidad y retrasos
- Análisis de cancelaciones y desvíos
- Análisis de rendimiento de las aerolíneas
- Análisis geográfico
- Análisis de factores de influencia


#### Fuente https://www.kaggle.com/datasets/mmetter/flights

In [41]:
import pandas as pd

In [42]:
# Se carga el Dataset
flights = pd.read_csv('../../data/flights.txt', sep= "|")

In [43]:
# Configuraraciones
pd.set_option('display.max_columns', None)

### Variables 

- FLIGHTDATE: Es la fecha del vuelo.
- AIRLINECODE: Es el código de la aerolínea.
- AIRLINENAME: Es el nombre de la aerolínea.
- TAILNUM: Es el número de cola de la aeronave, que identifica de manera única a una aeronave específica.
- FLIGHTNUM: Es el número de vuelo.
- ORIGINAIRPORTCODE: Es el código del aeropuerto de origen.
- ORIGAIRPORTNAME: Es el nombre del aeropuerto de origen.
- ORIGINCITYNAME: Es el nombre de la ciudad donde está ubicado el aeropuerto de origen.
- ORIGINSTATE: Es el estado donde está ubicado el aeropuerto de origen.
- ORIGINSTATENAME: Se refiere al nombre completo del estado donde está ubicado el aeropuerto de origen del vuelo
- DESTAIRPORTCODE: Este es el código del aeropuerto de destino al que se dirige el vuelo. 
- DESTAIRPORTNAME: Es el nombre del aeropuerto de destino al que se dirige el vuelo.
- DESTCITYNAME: Es el nombre de la ciudad donde está ubicado el aeropuerto de destino.
- DESTSTATE: Es el código del estado donde está ubicado el aeropuerto de destino.
- DESTSTATENAME: Es el nombre completo del estado donde está ubicado el aeropuerto de destino.
- CRSDEPTIME: Es la hora planificada de salida del vuelo. "CRS" significa "Computerized Reservation System".
- DEPTIME: Es la hora real de salida del vuelo.
- DEPDELAY: Es el retraso en la salida del vuelo, medido en minutos. Puede ser negativo si el vuelo sale antes de la hora programada.
- TAXIOUT: Es la duración del tiempo transcurrido desde el momento en que el avión se retira de la puerta de embarque hasta que despega. Es parte del tiempo de rodaje y preparación para el despegue.
- WHEELSON: Es el momento en que las ruedas del avión tocan el suelo al llegar a su destino.
- TAXIIN: Es la duración del tiempo transcurrido desde el momento en que las ruedas del avión tocan el suelo (wheels on) hasta que llega a la puerta del aeropuerto de destino.
- CRSARRTIME: Es la hora planificada de llegada del vuelo.
- ARRTIME: Es la hora real de llegada del vuelo.
- ARRDELAY: Es el retraso en la llegada del vuelo, medido en minutos.
- CRSELAPSEDTIME: Es el tiempo de vuelo planificado.
- ACTUALELAPSEDTIME: Es el tiempo de vuelo real.
- CANCELLED: Indica si el vuelo fue cancelado 
- DIVERTED: Indica si el vuelo fue desviado a otro aeropuerto  
- DISTANCE: Es la distancia del vuelo en millas.

In [44]:
flights.shape

(1191805, 31)

In [73]:
lista_variables = flights.columns.tolist()
print(lista_variables)

['FLIGHTDATE', 'AIRLINECODE', 'AIRLINENAME', 'TAILNUM', 'FLIGHTNUM', 'ORIGINAIRPORTCODE', 'ORIGAIRPORTNAME', 'ORIGINCITYNAME', 'ORIGINSTATE', 'ORIGINSTATENAME', 'DESTAIRPORTCODE', 'DESTAIRPORTNAME', 'DESTCITYNAME', 'DESTSTATE', 'DESTSTATENAME', 'CRSDEPTIME', 'DEPTIME', 'DEPDELAY', 'TAXIOUT', 'WHEELSOFF', 'WHEELSON', 'TAXIIN', 'CRSARRTIME', 'ARRTIME', 'ARRDELAY', 'CRSELAPSEDTIME', 'ACTUALELAPSEDTIME', 'CANCELLED', 'DIVERTED', 'DISTANCE']

In [46]:
flights.sample(3)

,TRANSACTIONID,FLIGHTDATE,AIRLINECODE,AIRLINENAME,TAILNUM,FLIGHTNUM,ORIGINAIRPORTCODE,ORIGAIRPORTNAME,ORIGINCITYNAME,ORIGINSTATE,ORIGINSTATENAME,DESTAIRPORTCODE,DESTAIRPORTNAME,DESTCITYNAME,DESTSTATE,DESTSTATENAME,CRSDEPTIME,DEPTIME,DEPDELAY,TAXIOUT,WHEELSOFF,WHEELSON,TAXIIN,CRSARRTIME,ARRTIME,ARRDELAY,CRSELAPSEDTIME,ACTUALELAPSEDTIME,CANCELLED,DIVERTED,DISTANCE
885037,118576000,20110904,EV,ExpressJet Airlines Inc.: EV,N659CA,5154,DTW,DetroitMI: Detroit Metro Wayne County,Detroit,MI,Michigan,ORF,NorfolkVA: Norfolk International,Norfolk,VA,Virginia,1022,1017.0,-5.0,14.0,1031.0,1148.0,2.0,1209,1150.0,-19.0,107.0,93.0,False,F,529 miles
1065307,34103400,19980531,AA,American Airlines Inc.: AA,N455AA,2221,PVD,ProvidenceRI: Theodore Francis Green State,Providence,RI,Rhode Island,ORD,ChicagoIL: Chicago O'Hare International,Chicago,IL,Illinois,852,849.0,-3.0,20.0,909.0,1028.0,6.0,1020,1034.0,14.0,148.0,165.0,False,False,849 miles
203631,27857100,19970123,WN,Southwest Airlines Co.: WN,N622,537,OAK,OaklandCA: Metropolitan Oakland International,Oakland,CA,California,LAX,Los AngelesCA: Los Angeles International,Los Angeles,CA,California,1230,1230.0,0.0,13.0,1243.0,1345.0,12.0,1345,1357.0,12.0,75.0,87.0,False,False,337 miles

In [47]:
# se eliminan las columnas innecesarias
flights = flights.drop(columns=['TRANSACTIONID'])

In [48]:
# se modifican los valores a enteros
columas = ['WHEELSON', 'TAXIIN', 'ARRDELAY', 'CRSELAPSEDTIME' , 'ACTUALELAPSEDTIME', 'ARRTIME', 'DEPDELAY', 'TAXIOUT', 'WHEELSOFF', 'WHEELSOFF', 'DEPTIME']

for column in columas:
    flights[column] = flights[column].astype(str).str.replace('.0', '', regex=False)

In [67]:
# se elimina "miles" de la variable distancia
flights['DISTANCE'] = flights['DISTANCE'].astype(str).str.replace(' miles', '', regex=False)

# luego se convierte a numerico
flights['DISTANCE'] = pd.to_numeric(flights['DISTANCE'])

In [68]:
# se transforma la columna de fecha a formato fecha
flights['FLIGHTDATE'] = pd.to_datetime(flights['FLIGHTDATE'], format='%Y%m%d')

In [69]:
flights.sample(3)

,FLIGHTDATE,AIRLINECODE,AIRLINENAME,TAILNUM,FLIGHTNUM,ORIGINAIRPORTCODE,ORIGAIRPORTNAME,ORIGINCITYNAME,ORIGINSTATE,ORIGINSTATENAME,DESTAIRPORTCODE,DESTAIRPORTNAME,DESTCITYNAME,DESTSTATE,DESTSTATENAME,CRSDEPTIME,DEPTIME,DEPDELAY,TAXIOUT,WHEELSOFF,WHEELSON,TAXIIN,CRSARRTIME,ARRTIME,ARRDELAY,CRSELAPSEDTIME,ACTUALELAPSEDTIME,CANCELLED,DIVERTED,DISTANCE
190178,2000-01-01,UA,United Air Lines Inc.: UA,N7295U,653,EWR,NewarkNJ: Newark Liberty International,Newark,NJ,New Jersey,ORD,ChicagoIL: Chicago O'Hare International,Chicago,IL,Illinois,1515,1508,-7,18,1526,1622,5,1634,1627,-7,139,139,F,False,719
111550,2002-05-16,AA,American Airlines Inc.: AA,N5CMAA,1296,LAX,Los AngelesCA: Los Angeles International,Los Angeles,CA,California,ORD,ChicagoIL: Chicago O'Hare International,Chicago,IL,Illinois,845,847,2,20,907,1431,10,1445,1441,-4,240,234,0,0,1745
860349,2001-01-05,NW,Northwest Airlines Inc.: NW,N783N3,1451,ORF,NorfolkVA: Norfolk International,Norfolk,VA,Virginia,DTW,DetroitMI: Detroit Metro Wayne County,Detroit,MI,Michigan,600,600,0,7,607,744,5,806,749,-17,126,109,False,False,529

In [60]:
# Se visualizan las ciudades
origen_ciudades = flights['ORIGINAIRPORTCODE'].unique()
print(origen_ciudades)

['ABQ' 'ABY' 'ALB' 'ABI' 'CAK' 'ATL' 'BHM' 'BIL' 'BGM' 'RDM' 'BET' 'BTR'
 'BPT' 'BLI' 'BJI' 'BRW' 'BGR' 'BWI' 'AUS' 'MDW' 'ORD' 'AMA' 'ACV' 'AGS'
 'ACY' 'ANC' 'ATW' 'ANI' 'AVL' 'APN' 'ABE' 'BFL' 'ASE' 'HTS' 'CLT' 'CRW'
 'CPR' 'CDC' 'CHS' 'CID' 'CMI' 'CLD' 'BTM' 'BTV' 'BUR' 'BQN' 'ADK' 'ABR'
 'AEX' 'TRI' 'BRO' 'BUF' 'BQK' 'BZN' 'BRD' 'BKG' 'BOS' 'BIS' 'BOI' 'DFW'
 'TYS' 'EYW' 'ILE' 'MCI' 'LMT' 'GRK' 'AKN' 'ISO' 'KTN' 'ADQ' 'LAS' 'LRD'
 'LAN' 'LAR' 'LCH' 'LNY' 'LFT' 'LSE' 'KOA' 'OTZ' 'ROR' 'LIH' 'LEX' 'LWS'
 'LAW' 'LWB' 'LBE' 'LIT' 'LNK' 'LGB' 'LAX' 'GGG' 'FCA' 'IAH' 'HOU' 'OGG'
 'AZO' 'JNU' 'JAX' 'JMS' 'JLN' 'OAJ' 'HSV' 'ISP' 'JAN' 'JAC' 'IND' 'ITH'
 'IYK' 'IMT' 'INL' 'IDA' 'HYA' 'EFD' 'SDF' 'MHT' 'MSN' 'MMH' 'LBB' 'LYH'
 'MCN' 'MFR' 'MQT' 'MVY' 'MAZ' 'RSW' 'MHK' 'MEM' 'MLB' 'HNL' 'MKK' 'BDL'
 'HLN' 'HDN' 'GSP' 'GSO' 'MSP' 'ITO' 'HOB' 'PIB' 'HIB' 'HYS' 'LGA' 'JFK'
 'MSY' 'EWR' 'ORF' 'OME' 'PHF' 'IAG' 'SWF' 'OAK' 'OTH' 'OKC' 'OMA' 'ONT'
 'MCO' 'BNA' 'HVN' 'EWN' 'MRY' 'MYR' 'CWA' 'MKG' 'ACK' 'APF' 'MTJ' 'MOB'
 'MGM' 'MWH' 'MLU' 'MLI' 'MFE' 'MOD' 'PNS' 'PHL' 'PSG' 'PSP' 'PIA' 'PSC'
 'PLN' 'ECP' 'PFN' 'OXR' 'PAH' 'PPG' 'MOT' 'CNY' 'MSO' 'MIB' 'MAF' 'MKE'
 'PHX' 'MIA' 'PIT' 'PDX' 'PWM' 'PSE' 'AZA' 'PIH' 'PBG' 'SMF' 'ROA' 'ROC'
 'RST' 'RIC' 'RDU' 'RNO' 'RHI' 'SAN' 'SAT' 'SJT' 'SLC' 'SFO' 'MBS' 'SPN'
 'RKS' 'ROW' 'ROP' 'RAP' 'RDD' 'FSD' 'SEA' 'STL' 'GEG' 'SHV' 'SBN' 'SIT'
 'SGU' 'SGF' 'SPI' 'UST' 'STC' 'SUX' 'TLH' 'TPA' 'SYR' 'SUN' 'SCE' 'KSM'
 'PIE' 'TUS' 'TTN' 'TVC' 'TOL' 'FOE' 'TXK' 'TEX' 'TUL' 'IAD' 'DCA' 'ACT'
 'VIS' 'VEL' 'VCT' 'VPS' 'VLD' 'DUT' 'UCA' 'TYR' 'TWF' 'PBI' 'ALO' 'ART'
 'HPN' 'ILM' 'ILG' 'ORH' 'WRG' 'ISN' 'SPS' 'ICT' 'YUM' 'YAK' 'WYS' 'SBA'
 'AVP' 'SAV' 'SRQ' 'CIU' 'SAF' 'SMX' 'SNA' 'SJC' 'SBP' 'SJU' 'DAL' 'PVD'
 'MEI' 'BMI' 'MDT' 'HRL' 'GUC' 'GPT' 'CMX' 'GST' 'GUM' 'GRR' 'GRB' 'GTF'
 'GJT' 'GFK' 'GNV' 'GCC' 'GCK' 'FAT' 'FWA' 'FSM' 'GRI' 'FLL' 'FAR' 'FAI'
 'EVV' 'XNA' 'FAY' 'FLG' 'DLH' 'EUG' 'ELM' 'ERI' 'ESC' 'EKO' 'ELP' 'DTW'
 'DRO' 'EAU' 'IPL' 'EGE' 'DBQ' 'DHN' 'DVL' 'DIK' 'DLG' 'STX' 'CVG' 'CIC'
 'CLE' 'CHA' 'CYS' 'CHO' 'STT' 'COS' 'CLL' 'COD' 'FNT' 'FLO' 'CMH' 'CSG'
 'GTR' 'DAY' 'CDV' 'CRP' 'DEN' 'DSM' 'DET' 'CEC' 'PUB' 'DAB' 'SCC' 'DRT'
 'COU' 'CAE' 'UTM']

In [59]:
# Se visualizan las ciudades
origen_estados = flights['ORIGINSTATENAME'].unique()
print(origen_estados)

['New Mexico' 'Georgia' 'New York' 'Texas' 'Ohio' 'Alabama' 'Montana'
 'Oregon' 'Alaska' 'Louisiana' 'Washington' 'Minnesota' 'Maine' 'Maryland'
 'Illinois' 'California' 'New Jersey' 'Wisconsin' 'North Carolina'
 'Michigan' 'Pennsylvania' 'Colorado' 'West Virginia' 'Wyoming' 'Utah'
 'South Carolina' 'Iowa' 'Vermont' 'Puerto Rico' 'South Dakota'
 'Tennessee' 'Missouri' 'Massachusetts' 'North Dakota' 'Idaho' 'Florida'
 'Nevada' 'Hawaii' 'U.S. Pacific Trust Territories and Possessions'
 'Kentucky' nan 'Arkansas' 'Nebraska' 'Mississippi' 'Indiana'
 'New Hampshire' 'Virginia' 'Connecticut' 'Arizona' 'Delaware'
 'Rhode Island' 'U.S. Virgin Islands']

In [58]:
# Se realiza una tabla de frecuencia de los estados.

ciudades_frecuencia = pd.DataFrame(flights['ORIGINSTATENAME'].value_counts())
ciudades_frecuencia.columns = ['Frecuencia']
ciudades_frecuencia.reset_index(inplace=True)
ciudades_frecuencia.columns = ['Categoria', 'Frecuencia']

ciudades_frecuencia.head(10)

        Categoria  Frecuencia
0      California      141852
1           Texas      137592
2        Illinois       78413
3         Florida       78338
4         Georgia       67182
5        New York       51653
6    Pennsylvania       39624
7        Colorado       39422
8  North Carolina       39249
9         Arizona       39024

In [72]:
flights.sample(3)

,FLIGHTDATE,AIRLINECODE,AIRLINENAME,TAILNUM,FLIGHTNUM,ORIGINAIRPORTCODE,ORIGAIRPORTNAME,ORIGINCITYNAME,ORIGINSTATE,ORIGINSTATENAME,DESTAIRPORTCODE,DESTAIRPORTNAME,DESTCITYNAME,DESTSTATE,DESTSTATENAME,CRSDEPTIME,DEPTIME,DEPDELAY,TAXIOUT,WHEELSOFF,WHEELSON,TAXIIN,CRSARRTIME,ARRTIME,ARRDELAY,CRSELAPSEDTIME,ACTUALELAPSEDTIME,CANCELLED,DIVERTED,DISTANCE
1015617,1998-09-01,WN,Southwest Airlines Co.: WN,N673,1610,TUL,TulsaOK: Tulsa International,Tulsa,NaN,NaN,DAL,DallasTX: Dallas Love Field,Dallas,TX,Texas,1135,1135,0,5,1140,1218,2,1225,1220,-5,50,45,0,0,237
120224,2009-09-23,MQ,Envoy Air: MQ,N847MQ,3093,LAX,Los AngelesCA: Los Angeles International,Los Angeles,CA,California,SAN,San DiegoCA: San Diego International,San Diego,CA,California,1755,1755,0,17,1812,1838,5,1845,1843,-2,50,48,F,False,109
345432,1994-09-13,TW,Trans World Airways LLC: TW,NaN,404,FSD,Sioux FallsSD: Joe Foss Field,Sioux Falls,SD,South Dakota,STL,St. LouisMO: Lambert-St. Louis International,St. Louis,MO,Missouri,1445,1442,-3,nan,nan,nan,nan,1612,1610,-2,87,88,0,0,471

In [56]:
fecha_mas_antigua = flights['FLIGHTDATE'].min()
fecha_mas_antigua

Timestamp('1992-01-01 00:00:00')

In [57]:
fecha_mas_reciente = flights['FLIGHTDATE'].max()
fecha_mas_reciente

Timestamp('2016-05-31 00:00:00')

In [70]:
# Se visualizan las categorias de las variables de cancelaciones
cancelaciones = flights['CANCELLED'].unique()
print(cancelaciones)

['F' 'False' '0' '1' 'True' 'T']

In [71]:
# Se visualizan las categorias de las variables de desvio
desvio = flights['DIVERTED'].unique()
print(desvio)

['False' 'F' '0' '1' 'True' 'T']